name: Deploy mdBook

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: XAMPPRocky/deploy-mdbook@v1
        with:
            token: ${{ secrets.GITHUB_TOKEN }}